### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by guidomz** [paskozdilar/venvrc#1]
Very useful script, thank you. Is there a way to make autocomplete to work in venv?

**Comment by paskozdilar** [comment]
Hi @guidomz, thank you for the suggestion.

I have added an autocomplete function to the `venvrc`.
You can update it by overwriting your current `~/.venvrc`.

Hope it does what you were hoping for.
Cheers!

**Comment by guidomz** [comment]
Salamat, @paskozdilar! It is indeed what I've been expecting.
